"""quickbooks_integration_5_tables

Revision ID: 0ac2200039d0
Revises: ee03acd94262
Create Date: 2026-02-13 08:29:46.304413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ac2200039d0'
down_revision: Union[str, None] = 'ee03acd94262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qb_connections',
    sa.Column('realm_id', sa.String(length=50), nullable=False, comment='QuickBooks company ID'),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted OAuth2 access token'),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted OAuth2 refresh token'),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_by', sa.Uuid(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True, comment='success | failed | in_progress'),
    sa.Column('company_info', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Cached QB company metadata'),
    sa.Column('webhook_verifier_token', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'realm_id', name='uq_qbconn_tenant_realm')
    )
    op.create_index(op.f('ix_qb_connections_tenant_id'), 'qb_connections', ['tenant_id'], unique=False)
    op.create_index('ix_qbconn_tenant_active', 'qb_connections', ['tenant_id', 'is_active'], unique=False)
    op.create_table('qb_account_mappings',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False, comment='income | cogs | tax_payable | bank | expense | discount | etc.'),
    sa.Column('pos_reference_id', sa.Uuid(), nullable=True, comment='e.g. category_id for category-level income mapping'),
    sa.Column('pos_reference_type', sa.String(length=50), nullable=True, comment='category | tax_rate | payment_method | modifier_group'),
    sa.Column('pos_reference_name', sa.String(length=255), nullable=True),
    sa.Column('qb_account_id', sa.String(length=50), nullable=False, comment='QuickBooks account ID'),
    sa.Column('qb_account_name', sa.String(length=255), nullable=False),
    sa.Column('qb_account_type', sa.String(length=50), nullable=False, comment='Income | Cost of Goods Sold | Expense | Other Current Liability | Bank | Equity etc.'),
    sa.Column('qb_account_sub_type', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_auto_created', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['qb_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qb_account_mappings_tenant_id'), 'qb_account_mappings', ['tenant_id'], unique=False)
    op.create_index('ix_qbacctmap_tenant_conn_type', 'qb_account_mappings', ['tenant_id', 'connection_id', 'mapping_type'], unique=False)
    op.create_table('qb_entity_mappings',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='menu_item | category | customer | tax_code | tax_rate | payment_method | vendor | class_ref | department | employee | discount_item | service_charge_item'),
    sa.Column('pos_entity_id', sa.Uuid(), nullable=False),
    sa.Column('pos_entity_name', sa.String(length=255), nullable=False),
    sa.Column('qb_entity_id', sa.String(length=50), nullable=False, comment='QuickBooks entity ID'),
    sa.Column('qb_entity_type', sa.String(length=50), nullable=False, comment='Item | Customer | TaxCode | TaxRate | PaymentMethod | Vendor | Class | Department | Employee'),
    sa.Column('qb_entity_name', sa.String(length=255), nullable=False),
    sa.Column('qb_entity_ref', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Full QB ref object for API calls'),
    sa.Column('sync_direction', sa.String(length=20), nullable=False, comment='pos_to_qb | qb_to_pos | bidirectional'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_hash', sa.String(length=64), nullable=True, comment='SHA-256 of last synced state'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['qb_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'connection_id', 'entity_type', 'pos_entity_id', name='uq_qbentmap_tenant_conn_type_entity')
    )
    op.create_index(op.f('ix_qb_entity_mappings_tenant_id'), 'qb_entity_mappings', ['tenant_id'], unique=False)
    op.create_index('ix_qbentmap_tenant_type', 'qb_entity_mappings', ['tenant_id', 'entity_type'], unique=False)
    op.create_table('qb_sync_log',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False, comment='Same values as job_type + oauth_connect | oauth_refresh | oauth_disconnect | account_create | webhook'),
    sa.Column('pos_entity_type', sa.String(length=50), nullable=True),
    sa.Column('pos_entity_id', sa.Uuid(), nullable=True),
    sa.Column('qb_entity_type', sa.String(length=50), nullable=True),
    sa.Column('qb_entity_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False, comment='create | update | delete | void | query | read | oauth'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success | failed | skipped | partial'),
    sa.Column('http_method', sa.String(length=10), nullable=True, comment='GET | POST | PUT | DELETE'),
    sa.Column('http_url', sa.String(length=500), nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='QuickBooks error code'),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('qb_doc_number', sa.String(length=50), nullable=True, comment='e.g. Sales Receipt number'),
    sa.Column('amount_paisa', sa.Integer(), nullable=True, comment='For quick financial audit (paisa)'),
    sa.Column('batch_id', sa.Uuid(), nullable=True, comment='Groups related sync operations'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['qb_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qb_sync_log_tenant_id'), 'qb_sync_log', ['tenant_id'], unique=False)
    op.create_index('ix_qbsynclog_tenant_batch', 'qb_sync_log', ['tenant_id', 'batch_id'], unique=False)
    op.create_index('ix_qbsynclog_tenant_entity', 'qb_sync_log', ['tenant_id', 'pos_entity_type', 'pos_entity_id'], unique=False)
    op.create_index('ix_qbsynclog_tenant_type_created', 'qb_sync_log', ['tenant_id', 'sync_type', 'created_at'], unique=False)
    op.create_table('qb_sync_queue',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False, comment='create_sales_receipt | create_credit_memo | sync_item | daily_summary | full_sync | etc.'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='order | order_void | order_refund | menu_item | category | customer | tax_config | payment_method | vendor | daily_close | chart_of_accounts'),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False, comment='0 = critical, 5 = normal, 10 = bulk'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | processing | completed | failed | dead_letter | cancelled'),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Serialized data for the sync operation'),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='QB API response data on success'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Full QB error response'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True, comment='Prevents duplicate syncs'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['qb_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_qbsyncq_tenant_idempotency')
    )
    op.create_index(op.f('ix_qb_sync_queue_tenant_id'), 'qb_sync_queue', ['tenant_id'], unique=False)
    op.create_index('ix_qbsyncq_tenant_retry', 'qb_sync_queue', ['tenant_id', 'next_retry_at'], unique=False)
    op.create_index('ix_qbsyncq_tenant_status_prio', 'qb_sync_queue', ['tenant_id', 'status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qbsyncq_tenant_status_prio', table_name='qb_sync_queue')
    op.drop_index('ix_qbsyncq_tenant_retry', table_name='qb_sync_queue')
    op.drop_index(op.f('ix_qb_sync_queue_tenant_id'), table_name='qb_sync_queue')
    op.drop_table('qb_sync_queue')
    op.drop_index('ix_qbsynclog_tenant_type_created', table_name='qb_sync_log')
    op.drop_index('ix_qbsynclog_tenant_entity', table_name='qb_sync_log')
    op.drop_index('ix_qbsynclog_tenant_batch', table_name='qb_sync_log')
    op.drop_index(op.f('ix_qb_sync_log_tenant_id'), table_name='qb_sync_log')
    op.drop_table('qb_sync_log')
    op.drop_index('ix_qbentmap_tenant_type', table_name='qb_entity_mappings')
    op.drop_index(op.f('ix_qb_entity_mappings_tenant_id'), table_name='qb_entity_mappings')
    op.drop_table('qb_entity_mappings')
    op.drop_index('ix_qbacctmap_tenant_conn_type', table_name='qb_account_mappings')
    op.drop_index(op.f('ix_qb_account_mappings_tenant_id'), table_name='qb_account_mappings')
    op.drop_table('qb_account_mappings')
    op.drop_index('ix_qbconn_tenant_active', table_name='qb_connections')
    op.drop_index(op.f('ix_qb_connections_tenant_id'), table_name='qb_connections')
    op.drop_table('qb_connections')
    # ### end Alembic commands ###
