"""phase4_floor_plan

Revision ID: b23ab0200c28
Revises: 02577b9f3600
Create Date: 2026-02-10 15:09:37.307324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23ab0200c28'
down_revision: Union[str, None] = '02577b9f3600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_floor_tenant_name')
    )
    op.create_index(op.f('ix_floors_tenant_id'), 'floors', ['tenant_id'], unique=False)
    op.create_table('tables',
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True, comment="Optional display label (e.g. 'VIP-1')"),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False, comment='Rotation in degrees (0-360)'),
    sa.Column('shape', sa.String(length=20), nullable=False, comment='square | round | rectangle'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='available | occupied | reserved | cleaning'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'floor_id', 'number', name='uq_table_tenant_floor_number')
    )
    op.create_index(op.f('ix_tables_floor_id'), 'tables', ['floor_id'], unique=False)
    op.create_index(op.f('ix_tables_tenant_id'), 'tables', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_tenant_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_floor_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_floors_tenant_id'), table_name='floors')
    op.drop_table('floors')
    # ### end Alembic commands ###
