"""phase5_orders

Revision ID: ee03acd94262
Revises: b23ab0200c28
Create Date: 2026-02-10 16:13:03.814945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee03acd94262'
down_revision: Union[str, None] = 'b23ab0200c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='dine_in | takeaway | call_center'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | confirmed | in_kitchen | ready | served | completed | voided'),
    sa.Column('payment_status', sa.String(length=20), nullable=False, comment='unpaid | partial | paid | refunded'),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False, comment='Subtotal in paisa'),
    sa.Column('tax_amount', sa.Integer(), nullable=False, comment='Tax in paisa'),
    sa.Column('discount_amount', sa.Integer(), nullable=False, comment='Discount in paisa'),
    sa.Column('total', sa.Integer(), nullable=False, comment='Grand total in paisa'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'order_number', name='uq_order_tenant_number')
    )
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_index('ix_orders_tenant_created', 'orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index('ix_orders_tenant_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='Unit price in paisa (base + modifiers)'),
    sa.Column('total', sa.Integer(), nullable=False, comment='unit_price * quantity in paisa'),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | sent | preparing | ready | served'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_tenant_id'), 'order_items', ['tenant_id'], unique=False)
    op.create_table('order_status_log',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True, comment='Null for initial creation'),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_log_order_id'), 'order_status_log', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_log_tenant_id'), 'order_status_log', ['tenant_id'], unique=False)
    op.create_table('order_item_modifiers',
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('modifier_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_adjustment', sa.Integer(), nullable=False, comment='Price adjustment in paisa'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_modifiers_order_item_id'), 'order_item_modifiers', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_item_modifiers_tenant_id'), 'order_item_modifiers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_modifiers_tenant_id'), table_name='order_item_modifiers')
    op.drop_index(op.f('ix_order_item_modifiers_order_item_id'), table_name='order_item_modifiers')
    op.drop_table('order_item_modifiers')
    op.drop_index(op.f('ix_order_status_log_tenant_id'), table_name='order_status_log')
    op.drop_index(op.f('ix_order_status_log_order_id'), table_name='order_status_log')
    op.drop_table('order_status_log')
    op.drop_index(op.f('ix_order_items_tenant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_tenant_status', table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index('ix_orders_tenant_created', table_name='orders')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
