"""QBXML builder for Customers.

Converts POS customers to QuickBooks Desktop Customer entities.

A Customer in QB Desktop is required for all transactions (sales receipts, invoices, etc.).
POS supports:
- Walk-in customers (default, no details)
- Call center customers (phone, address, order history)
- Delivery customers (address required)
"""

import logging
from typing import Any
from lxml import etree

from app.services.quickbooks.qbxml.constants import FIELD_LIMITS

logger = logging.getLogger(__name__)


def truncate_field(value: str, field_name: str) -> str:
    """Truncate a field to QB's maximum length."""
    limit = FIELD_LIMITS.get(field_name)
    if limit and isinstance(limit, int) and len(value) > limit:
        logger.warning(
            "Truncating %s from %d to %d chars: %s...",
            field_name,
            len(value),
            limit,
            value[:30],
        )
        return value[:limit]
    return value


def build_customer_add_rq(customer_data: dict[str, Any]) -> str:
    """Build a CustomerAddRq QBXML request.

    Args:
        customer_data: POS customer dict with keys:
            - name: str (required, max 41 chars)
            - phone: str (optional, format: +92-XXX-XXXXXXX)
            - email: str (optional, max 1023 chars)
            - address: dict (optional) with keys:
                - line1, line2, line3, city, state, postal_code, country
            - notes: str (optional)
            - customer_type: str (optional, e.g., "walk-in", "regular", "corporate")

    Returns:
        QBXML string ready to send via QBWC.

    Example:
        >>> xml = build_customer_add_rq({
        ...     "name": "Ahmed Khan",
        ...     "phone": "+92-300-1234567",
        ...     "email": "ahmed@example.com",
        ...     "address": {
        ...         "line1": "House 123, Street 5",
        ...         "line2": "F-7 Markaz",
        ...         "city": "Islamabad",
        ...         "state": "Islamabad Capital Territory",
        ...         "postal_code": "44000",
        ...         "country": "Pakistan",
        ...     },
        ...     "notes": "Regular customer, prefers delivery",
        ... })
        >>> print(xml)  # Valid QBXML
    """
    # Validate required fields
    if not customer_data.get("name"):
        raise ValueError("name is required")

    # Extract customer fields
    name = truncate_field(customer_data["name"], "Name")
    phone = customer_data.get("phone", "")
    email = customer_data.get("email", "")
    notes = customer_data.get("notes", "")
    address = customer_data.get("address", {})

    # Build QBXML
    root = etree.Element("QBXML")
    root.append(etree.Comment(f" Generated by Sitara POS - Customer: {name} "))

    qbxml_msgs_rq = etree.SubElement(root, "QBXMLMsgsRq", onError="stopOnError")
    customer_add_rq = etree.SubElement(qbxml_msgs_rq, "CustomerAddRq", requestID="1")
    customer_add = etree.SubElement(customer_add_rq, "CustomerAdd")

    # Name (required)
    etree.SubElement(customer_add, "Name").text = name

    # Company name (optional, same as name for individuals)
    if customer_data.get("company_name"):
        company_name = truncate_field(customer_data["company_name"], "Name")
        etree.SubElement(customer_add, "CompanyName").text = company_name

    # Phone
    if phone:
        phone_clean = truncate_field(phone, "Phone")
        etree.SubElement(customer_add, "Phone").text = phone_clean

    # Email
    if email:
        email_clean = truncate_field(email, "Email")
        etree.SubElement(customer_add, "Email").text = email_clean

    # Billing Address
    if address:
        addr_elem = etree.SubElement(customer_add, "BillAddress")

        # Address lines (Addr1-5)
        addr_limits = FIELD_LIMITS.get("Address", {})
        if address.get("line1"):
            line1 = address["line1"][:addr_limits.get("Addr1", 41)]
            etree.SubElement(addr_elem, "Addr1").text = line1
        if address.get("line2"):
            line2 = address["line2"][:addr_limits.get("Addr2", 41)]
            etree.SubElement(addr_elem, "Addr2").text = line2
        if address.get("line3"):
            line3 = address["line3"][:addr_limits.get("Addr3", 41)]
            etree.SubElement(addr_elem, "Addr3").text = line3

        # City, State, PostalCode, Country
        if address.get("city"):
            city = address["city"][:addr_limits.get("City", 31)]
            etree.SubElement(addr_elem, "City").text = city
        if address.get("state"):
            state = address["state"][:addr_limits.get("State", 21)]
            etree.SubElement(addr_elem, "State").text = state
        if address.get("postal_code"):
            postal = address["postal_code"][:addr_limits.get("PostalCode", 13)]
            etree.SubElement(addr_elem, "PostalCode").text = postal
        if address.get("country"):
            country = address["country"][:addr_limits.get("Country", 31)]
            etree.SubElement(addr_elem, "Country").text = country

    # Notes
    if notes:
        notes_clean = truncate_field(notes, "Description")
        etree.SubElement(customer_add, "Notes").text = notes_clean

    # Convert to string
    qbxml_str = etree.tostring(
        root,
        pretty_print=True,
        xml_declaration=True,
        encoding="UTF-8",
    ).decode("utf-8")

    logger.info("Built CustomerAddRq for customer: %s", name)

    return qbxml_str


def build_customer_mod_rq(
    customer_data: dict[str, Any],
    list_id: str,
    edit_sequence: str,
) -> str:
    """Build a CustomerModRq QBXML request (for updates).

    Args:
        customer_data: POS customer dict (same format as CustomerAddRq)
        list_id: QB-assigned ListID (from previous CustomerAddRs response)
        edit_sequence: QB-assigned EditSequence (from QB, prevents conflicts)

    Returns:
        QBXML string ready to send via QBWC.

    Note:
        QB Desktop requires ListID + EditSequence for updates to prevent
        concurrent modification conflicts.
    """
    # Validate required fields
    if not list_id:
        raise ValueError("list_id is required for CustomerMod")
    if not edit_sequence:
        raise ValueError("edit_sequence is required for CustomerMod")

    name = customer_data.get("name", "")
    phone = customer_data.get("phone", "")
    email = customer_data.get("email", "")
    notes = customer_data.get("notes", "")
    address = customer_data.get("address", {})

    # Build QBXML
    root = etree.Element("QBXML")
    root.append(etree.Comment(f" Generated by Sitara POS - Update Customer {name} "))

    qbxml_msgs_rq = etree.SubElement(root, "QBXMLMsgsRq", onError="stopOnError")
    customer_mod_rq = etree.SubElement(qbxml_msgs_rq, "CustomerModRq", requestID="1")
    customer_mod = etree.SubElement(customer_mod_rq, "CustomerMod")

    # ListID + EditSequence (required for updates)
    etree.SubElement(customer_mod, "ListID").text = list_id
    etree.SubElement(customer_mod, "EditSequence").text = edit_sequence

    # Name (if changed)
    if name:
        name_clean = truncate_field(name, "Name")
        etree.SubElement(customer_mod, "Name").text = name_clean

    # Phone
    if phone:
        phone_clean = truncate_field(phone, "Phone")
        etree.SubElement(customer_mod, "Phone").text = phone_clean

    # Email
    if email:
        email_clean = truncate_field(email, "Email")
        etree.SubElement(customer_mod, "Email").text = email_clean

    # Billing Address (if provided)
    if address:
        addr_elem = etree.SubElement(customer_mod, "BillAddress")
        addr_limits = FIELD_LIMITS.get("Address", {})

        if address.get("line1"):
            etree.SubElement(addr_elem, "Addr1").text = address["line1"][:addr_limits.get("Addr1", 41)]
        if address.get("line2"):
            etree.SubElement(addr_elem, "Addr2").text = address["line2"][:addr_limits.get("Addr2", 41)]
        if address.get("city"):
            etree.SubElement(addr_elem, "City").text = address["city"][:addr_limits.get("City", 31)]
        if address.get("state"):
            etree.SubElement(addr_elem, "State").text = address["state"][:addr_limits.get("State", 21)]
        if address.get("postal_code"):
            etree.SubElement(addr_elem, "PostalCode").text = address["postal_code"][:addr_limits.get("PostalCode", 13)]
        if address.get("country"):
            etree.SubElement(addr_elem, "Country").text = address["country"][:addr_limits.get("Country", 31)]

    # Notes
    if notes:
        notes_clean = truncate_field(notes, "Description")
        etree.SubElement(customer_mod, "Notes").text = notes_clean

    # Convert to string
    qbxml_str = etree.tostring(
        root,
        pretty_print=True,
        xml_declaration=True,
        encoding="UTF-8",
    ).decode("utf-8")

    logger.info("Built CustomerModRq for ListID: %s", list_id)

    return qbxml_str
