"""QBXML builder for Items.

Converts POS menu items to QuickBooks Desktop Item entities.

Item types in QB Desktop:
- ItemNonInventory: Service items (our POS menu items sync as this)
- ItemInventory: Tracked inventory (for BOM ingredients - Week 6)
- ItemInventoryAssembly: Recipe/BOM items (Week 6)

For now, we sync POS menu items as NonInventory service items (no stock tracking).
"""

import logging
from decimal import Decimal, ROUND_HALF_UP
from typing import Any
from lxml import etree

from app.services.quickbooks.qbxml.constants import FIELD_LIMITS

logger = logging.getLogger(__name__)


def paisa_to_decimal(paisa: int) -> str:
    """Convert paisa to decimal string."""
    d = Decimal(paisa) / Decimal(100)
    return str(d.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def truncate_field(value: str, field_name: str) -> str:
    """Truncate a field to QB's maximum length."""
    limit = FIELD_LIMITS.get(field_name)
    if limit and isinstance(limit, int) and len(value) > limit:
        logger.warning(
            "Truncating %s from %d to %d chars: %s...",
            field_name,
            len(value),
            limit,
            value[:30],
        )
        return value[:limit]
    return value


def build_item_non_inventory_add_rq(
    item_data: dict[str, Any],
    income_account: str,  # QB account name (e.g., "Food Sales")
    expense_account: str | None = None,  # Optional (e.g., "Cost of Food")
) -> str:
    """Build an ItemNonInventoryAddRq QBXML request.

    Args:
        item_data: POS menu item dict with keys:
            - name: str (required, max 41 chars)
            - description: str (optional, max 4095 chars)
            - price_paisa: int (required, selling price)
            - category: str (optional, QB parent item for hierarchy)
            - is_active: bool (default True)
            - sku: str (optional, for POS tracking)
        income_account: QB income account name (where revenue is recorded)
        expense_account: QB expense/COGS account (optional, for purchase tracking)

    Returns:
        QBXML string ready to send via QBWC.

    Example:
        >>> xml = build_item_non_inventory_add_rq(
        ...     item_data={
        ...         "name": "Chicken Biryani",
        ...         "description": "Aromatic basmati rice with spiced chicken",
        ...         "price_paisa": 85000,  # Rs. 850
        ...         "category": "Main Courses",
        ...         "is_active": True,
        ...     },
        ...     income_account="Food Sales",
        ...     expense_account="Cost of Food",
        ... )
        >>> print(xml)  # Valid QBXML
    """
    # Validate required fields
    if not item_data.get("name"):
        raise ValueError("name is required")
    if not item_data.get("price_paisa"):
        raise ValueError("price_paisa is required")

    # Extract item fields
    name = truncate_field(item_data["name"], "Name")
    description = item_data.get("description", "")
    price_paisa = item_data["price_paisa"]
    category = item_data.get("category", "")
    is_active = item_data.get("is_active", True)
    sku = item_data.get("sku", "")

    # Build QBXML
    root = etree.Element("QBXML")
    root.append(etree.Comment(f" Generated by Sitara POS - Item: {name} "))

    qbxml_msgs_rq = etree.SubElement(root, "QBXMLMsgsRq", onError="stopOnError")
    item_add_rq = etree.SubElement(qbxml_msgs_rq, "ItemNonInventoryAddRq", requestID="1")
    item_add = etree.SubElement(item_add_rq, "ItemNonInventoryAdd")

    # Name (required, max 41 chars)
    etree.SubElement(item_add, "Name").text = name

    # IsActive
    etree.SubElement(item_add, "IsActive").text = "true" if is_active else "false"

    # Parent (category, for hierarchical organization)
    if category:
        parent_ref = etree.SubElement(item_add, "ParentRef")
        category_clean = truncate_field(category, "Name")
        etree.SubElement(parent_ref, "FullName").text = category_clean

    # Sales Description
    if description:
        desc_clean = truncate_field(description, "Description")
        etree.SubElement(item_add, "SalesDesc").text = desc_clean

    # Sales Price
    price_decimal = paisa_to_decimal(price_paisa)
    etree.SubElement(item_add, "SalesPrice").text = price_decimal

    # Income Account (where revenue is recorded)
    income_ref = etree.SubElement(item_add, "IncomeAccountRef")
    etree.SubElement(income_ref, "FullName").text = income_account

    # Expense Account (optional, for cost tracking)
    if expense_account:
        expense_ref = etree.SubElement(item_add, "ExpenseAccountRef")
        etree.SubElement(expense_ref, "FullName").text = expense_account

    # Convert to string
    qbxml_str = etree.tostring(
        root,
        pretty_print=True,
        xml_declaration=True,
        encoding="UTF-8",
    ).decode("utf-8")

    logger.info(
        "Built ItemNonInventoryAddRq for item: %s (price: %s PKR)",
        name,
        price_decimal,
    )

    return qbxml_str


def build_item_non_inventory_mod_rq(
    item_data: dict[str, Any],
    list_id: str,
    edit_sequence: str,
    income_account: str | None = None,
    expense_account: str | None = None,
) -> str:
    """Build an ItemNonInventoryModRq QBXML request (for updates).

    Args:
        item_data: POS menu item dict (same format as Add)
        list_id: QB-assigned ListID
        edit_sequence: QB-assigned EditSequence
        income_account: Optional (only if changing account)
        expense_account: Optional (only if changing account)

    Returns:
        QBXML string ready to send via QBWC.
    """
    # Validate required fields
    if not list_id:
        raise ValueError("list_id is required for ItemMod")
    if not edit_sequence:
        raise ValueError("edit_sequence is required for ItemMod")

    name = item_data.get("name", "")
    description = item_data.get("description", "")
    price_paisa = item_data.get("price_paisa")
    is_active = item_data.get("is_active")

    # Build QBXML
    root = etree.Element("QBXML")
    root.append(etree.Comment(f" Generated by Sitara POS - Update Item {name} "))

    qbxml_msgs_rq = etree.SubElement(root, "QBXMLMsgsRq", onError="stopOnError")
    item_mod_rq = etree.SubElement(qbxml_msgs_rq, "ItemNonInventoryModRq", requestID="1")
    item_mod = etree.SubElement(item_mod_rq, "ItemNonInventoryMod")

    # ListID + EditSequence (required for updates)
    etree.SubElement(item_mod, "ListID").text = list_id
    etree.SubElement(item_mod, "EditSequence").text = edit_sequence

    # Name (if changed)
    if name:
        name_clean = truncate_field(name, "Name")
        etree.SubElement(item_mod, "Name").text = name_clean

    # IsActive (if specified)
    if is_active is not None:
        etree.SubElement(item_mod, "IsActive").text = "true" if is_active else "false"

    # Sales Description
    if description:
        desc_clean = truncate_field(description, "Description")
        etree.SubElement(item_mod, "SalesDesc").text = desc_clean

    # Sales Price
    if price_paisa:
        price_decimal = paisa_to_decimal(price_paisa)
        etree.SubElement(item_mod, "SalesPrice").text = price_decimal

    # Income Account (if changing)
    if income_account:
        income_ref = etree.SubElement(item_mod, "IncomeAccountRef")
        etree.SubElement(income_ref, "FullName").text = income_account

    # Expense Account (if changing)
    if expense_account:
        expense_ref = etree.SubElement(item_mod, "ExpenseAccountRef")
        etree.SubElement(expense_ref, "FullName").text = expense_account

    # Convert to string
    qbxml_str = etree.tostring(
        root,
        pretty_print=True,
        xml_declaration=True,
        encoding="UTF-8",
    ).decode("utf-8")

    logger.info("Built ItemNonInventoryModRq for ListID: %s", list_id)

    return qbxml_str
