import { useEffect, useState } from "react";
import {
  FileText,
  Loader2,
  Printer,
  DollarSign,
  ShoppingCart,
  CreditCard,
  TrendingUp,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { formatPKR } from "@/utils/currency";
import api from "@/lib/axios";

interface DrawerSummary {
  opening_float: number;
  cash_in: number;
  cash_out_change: number;
  cash_out_refund: number;
  expected_balance: number;
  counted_balance: number | null;
  variance: number | null;
  session_status: string | null;
}

interface ZReport {
  date: string;
  generated_at: string;
  generated_by: string;
  drawer: DrawerSummary | null;
  total_orders: number;
  total_revenue: number;
  total_tax: number;
  total_discount: number;
  by_channel: { channel: string; orders: number; revenue: number }[];
  by_payment_method: { method: string; count: number; total: number }[];
  by_status: { status: string; count: number }[];
  top_items: { name: string; quantity: number; revenue: number }[];
}

const channelLabels: Record<string, string> = {
  dine_in: "Dine-In",
  takeaway: "Takeaway",
  call_center: "Call Center",
};

function getToday(): string {
  return new Date().toISOString().split("T")[0] ?? "";
}

function ZReportPage() {
  const { toast } = useToast();
  const [selectedDate, setSelectedDate] = useState(getToday);
  const [report, setReport] = useState<ZReport | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (selectedDate) fetchReport();
  }, [selectedDate]);

  async function fetchReport() {
    try {
      setLoading(true);
      const { data } = await api.get<ZReport>(
        `/reports/z-report?date=${selectedDate}`
      );
      setReport(data);
    } catch {
      toast({ title: "Failed to load Z-Report", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-primary-600" />
      </div>
    );
  }

  return (
    <div className="space-y-6 print:space-y-4">
      {/* Header (hidden in print) */}
      <div className="flex items-center justify-between print:hidden">
        <div className="flex items-center gap-3">
          <FileText className="h-7 w-7 text-primary-600" />
          <h1 className="text-pos-2xl font-bold text-secondary-900">
            Z-Report / Daily Settlement
          </h1>
        </div>
        <div className="flex items-center gap-3">
          <input
            type="date"
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            className="min-h-[48px] rounded-md border border-secondary-300 px-3 text-pos-sm"
          />
          <Button
            onClick={handlePrint}
            disabled={!report}
            className="min-h-[48px] gap-2"
          >
            <Printer className="h-4 w-4" />
            Print
          </Button>
        </div>
      </div>

      {/* Print-only header */}
      <div className="hidden text-center print:block">
        <h1 className="text-lg font-bold">Z-Report — Daily Settlement</h1>
        <p className="text-sm">Date: {selectedDate}</p>
        {report && (
          <p className="text-xs text-secondary-500">
            Generated by {report.generated_by} at{" "}
            {new Date(report.generated_at).toLocaleString("en-PK")}
          </p>
        )}
      </div>

      {!report ? (
        <div className="py-12 text-center text-secondary-500">
          No data for this date.
        </div>
      ) : (
        <>
          {/* KPI Cards */}
          <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
            <KpiCard
              icon={<ShoppingCart className="h-5 w-5" />}
              label="Total Orders"
              value={report.total_orders.toString()}
            />
            <KpiCard
              icon={<DollarSign className="h-5 w-5" />}
              label="Total Revenue"
              value={formatPKR(report.total_revenue)}
            />
            <KpiCard
              icon={<TrendingUp className="h-5 w-5" />}
              label="Tax Collected"
              value={formatPKR(report.total_tax)}
            />
            <KpiCard
              icon={<CreditCard className="h-5 w-5" />}
              label="Discounts"
              value={formatPKR(report.total_discount)}
            />
          </div>

          <div className="grid gap-6 lg:grid-cols-2">
            {/* Cash Drawer */}
            {report.drawer && (
              <Card>
                <CardContent className="space-y-3 pt-6">
                  <h2 className="font-semibold text-secondary-800">
                    Cash Drawer
                    {report.drawer.session_status && (
                      <Badge
                        className={`ml-2 ${
                          report.drawer.session_status === "open"
                            ? "bg-green-100 text-green-800"
                            : "bg-secondary-100 text-secondary-600"
                        }`}
                      >
                        {report.drawer.session_status}
                      </Badge>
                    )}
                  </h2>
                  <div className="space-y-1 text-pos-sm">
                    <Row label="Opening Float" value={formatPKR(report.drawer.opening_float)} />
                    <Row label="Cash In (Sales)" value={formatPKR(report.drawer.cash_in)} />
                    <Row label="Cash Out (Change)" value={`-${formatPKR(report.drawer.cash_out_change)}`} />
                    <Row label="Cash Out (Refunds)" value={`-${formatPKR(report.drawer.cash_out_refund)}`} />
                    <div className="border-t pt-1" />
                    <Row label="Expected Balance" value={formatPKR(report.drawer.expected_balance)} bold />
                    {report.drawer.counted_balance != null && (
                      <>
                        <Row label="Counted Balance" value={formatPKR(report.drawer.counted_balance)} />
                        <Row
                          label="Variance"
                          value={formatPKR(report.drawer.variance ?? 0)}
                          bold
                          variant={
                            (report.drawer.variance ?? 0) === 0
                              ? "neutral"
                              : (report.drawer.variance ?? 0) > 0
                                ? "positive"
                                : "negative"
                          }
                        />
                      </>
                    )}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* By Channel */}
            <Card>
              <CardContent className="space-y-3 pt-6">
                <h2 className="font-semibold text-secondary-800">
                  Sales by Channel
                </h2>
                {report.by_channel.length === 0 ? (
                  <p className="text-pos-sm text-secondary-500">No sales</p>
                ) : (
                  <div className="space-y-2 text-pos-sm">
                    {report.by_channel.map((ch) => (
                      <div
                        key={ch.channel}
                        className="flex items-center justify-between rounded-lg bg-secondary-50 px-3 py-2"
                      >
                        <span className="font-medium">
                          {channelLabels[ch.channel] ?? ch.channel}
                        </span>
                        <span>
                          {ch.orders} orders — {formatPKR(ch.revenue)}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* By Payment Method */}
            <Card>
              <CardContent className="space-y-3 pt-6">
                <h2 className="font-semibold text-secondary-800">
                  By Payment Method
                </h2>
                {report.by_payment_method.length === 0 ? (
                  <p className="text-pos-sm text-secondary-500">
                    No payments recorded
                  </p>
                ) : (
                  <div className="space-y-2 text-pos-sm">
                    {report.by_payment_method.map((pm) => (
                      <div
                        key={pm.method}
                        className="flex items-center justify-between rounded-lg bg-secondary-50 px-3 py-2"
                      >
                        <span className="font-medium">{pm.method}</span>
                        <span>
                          {pm.count}x — {formatPKR(pm.total)}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Order Status Breakdown */}
            <Card>
              <CardContent className="space-y-3 pt-6">
                <h2 className="font-semibold text-secondary-800">
                  Order Status
                </h2>
                <div className="flex flex-wrap gap-2">
                  {report.by_status.map((s) => (
                    <Badge key={s.status} variant="outline" className="text-pos-sm">
                      {s.status}: {s.count}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Top Items */}
          {report.top_items.length > 0 && (
            <Card>
              <CardContent className="pt-6">
                <h2 className="mb-3 font-semibold text-secondary-800">
                  Top 10 Items
                </h2>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-pos-sm">
                    <thead>
                      <tr className="border-b text-secondary-500">
                        <th className="pb-2 font-medium">#</th>
                        <th className="pb-2 font-medium">Item</th>
                        <th className="pb-2 font-medium text-right">Qty</th>
                        <th className="pb-2 font-medium text-right">Revenue</th>
                      </tr>
                    </thead>
                    <tbody>
                      {report.top_items.map((item, i) => (
                        <tr key={i} className="border-b last:border-0">
                          <td className="py-2 text-secondary-500">{i + 1}</td>
                          <td className="py-2 font-medium">{item.name}</td>
                          <td className="py-2 text-right">{item.quantity}</td>
                          <td className="py-2 text-right">
                            {formatPKR(item.revenue)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}

/* ---------- helpers ---------- */

function KpiCard({
  icon,
  label,
  value,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
}) {
  return (
    <Card>
      <CardContent className="flex items-center gap-3 pt-6">
        <div className="rounded-lg bg-primary-100 p-2 text-primary-600">
          {icon}
        </div>
        <div>
          <p className="text-pos-sm text-secondary-500">{label}</p>
          <p className="text-pos-lg font-bold text-secondary-900">{value}</p>
        </div>
      </CardContent>
    </Card>
  );
}

function Row({
  label,
  value,
  bold,
  variant,
}: {
  label: string;
  value: string;
  bold?: boolean;
  variant?: "neutral" | "positive" | "negative";
}) {
  const variantClass =
    variant === "positive"
      ? "text-green-600"
      : variant === "negative"
        ? "text-red-600"
        : "";

  return (
    <div className="flex justify-between">
      <span className={bold ? "font-semibold" : ""}>{label}</span>
      <span className={`${bold ? "font-semibold" : ""} ${variantClass}`}>
        {value}
      </span>
    </div>
  );
}

export default ZReportPage;
