import { useEffect, useState } from "react";
import {
  FileText,
  Loader2,
  Printer,
  DollarSign,
  ShoppingCart,
  CreditCard,
  TrendingUp,
  RotateCcw,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { formatPKR } from "@/utils/currency";
import api from "@/lib/axios";

interface DrawerSummary {
  opening_float: number;
  cash_in: number;
  cash_out_change: number;
  cash_out_refund: number;
  expected_balance: number;
  counted_balance: number | null;
  variance: number | null;
  session_status: string | null;
}

interface ZReport {
  date: string;
  generated_at: string;
  generated_by: string;
  drawer: DrawerSummary | null;
  total_orders: number;
  total_revenue: number;
  total_tax: number;
  total_discount: number;
  settled_orders: number;
  fully_refunded_orders: number;
  net_tax: number;
  by_channel: { channel: string; orders: number; revenue: number }[];
  by_payment_method: {
    method: string;
    count: number;
    total: number;
    payment_count: number;
    refund_count: number;
    gross_total: number;
    refund_total: number;
    net_total: number;
  }[];
  by_status: { status: string; count: number }[];
  top_items: { name: string; quantity: number; revenue: number }[];
}

const channelLabels: Record<string, string> = {
  dine_in: "Dine-In",
  takeaway: "Takeaway",
  call_center: "Call Center",
};

function getToday(): string {
  return new Date().toISOString().split("T")[0] ?? "";
}

function ZReportPage() {
  const { toast } = useToast();
  const [selectedDate, setSelectedDate] = useState(getToday);
  const [report, setReport] = useState<ZReport | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (selectedDate) fetchReport();
  }, [selectedDate]);

  async function fetchReport() {
    try {
      setLoading(true);
      const { data } = await api.get<ZReport>(
        `/reports/z-report?date=${selectedDate}`
      );
      setReport(data);
    } catch {
      toast({ title: "Failed to load Z-Report", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-primary-600" />
      </div>
    );
  }

  return (
    <div className="print-clean">
      {/* ===== SCREEN HEADER (hidden in print) ===== */}
      <div className="mb-6 flex items-center justify-between print:hidden">
        <div className="flex items-center gap-3">
          <FileText className="h-7 w-7 text-primary-600" />
          <h1 className="text-pos-2xl font-bold text-secondary-900">
            Z-Report / Daily Settlement
          </h1>
        </div>
        <div className="flex items-center gap-3">
          <input
            type="date"
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            className="min-h-[48px] rounded-md border border-secondary-300 px-3 text-pos-sm"
          />
          <Button
            onClick={handlePrint}
            disabled={!report}
            className="min-h-[48px] gap-2"
          >
            <Printer className="h-4 w-4" />
            Print
          </Button>
        </div>
      </div>

      {/* ===== PRINT HEADER (hidden on screen) ===== */}
      <div className="hidden print:block print:mb-6">
        <div className="border-b-2 border-black pb-3 mb-4">
          <h1 className="text-xl font-bold text-center">Z-Report — Daily Settlement</h1>
          <p className="text-center text-sm mt-1">Date: {selectedDate}</p>
          {report && (
            <p className="text-center text-xs text-gray-500 mt-1">
              Generated by {report.generated_by} at{" "}
              {new Date(report.generated_at).toLocaleString("en-PK")}
            </p>
          )}
        </div>
      </div>

      {!report ? (
        <div className="py-12 text-center text-secondary-500">
          No data for this date.
        </div>
      ) : (
        <div className="space-y-6 print:space-y-4">
          {/* ===== KPI SUMMARY ===== */}
          {/* Screen: card grid */}
          <div className="grid grid-cols-2 gap-4 lg:grid-cols-3 xl:grid-cols-5 print:hidden">
            <KpiCard
              icon={<ShoppingCart className="h-5 w-5" />}
              label="Settled Orders"
              value={report.settled_orders.toString()}
            />
            <KpiCard
              icon={<RotateCcw className="h-5 w-5" />}
              label="Fully Refunded"
              value={report.fully_refunded_orders.toString()}
            />
            <KpiCard
              icon={<DollarSign className="h-5 w-5" />}
              label="Net Revenue"
              value={formatPKR(report.net_revenue)}
            />
            <KpiCard
              icon={<TrendingUp className="h-5 w-5" />}
              label="Net Tax Collected"
              value={formatPKR(report.net_tax)}
            />
            <KpiCard
              icon={<CreditCard className="h-5 w-5" />}
              label="Discounts"
              value={formatPKR(report.total_discount)}
            />
          </div>

          {/* Print: compact summary table */}
          <div className="hidden print:block print-section">
            <h2 className="text-sm font-bold uppercase tracking-wide border-b border-gray-300 pb-1 mb-2">Summary</h2>
            <table className="w-full text-sm">
              <tbody>
                <tr><td className="py-1">Settled Orders</td><td className="py-1 text-right font-semibold">{report.settled_orders}</td></tr>
                <tr><td className="py-1">Fully Refunded Orders</td><td className="py-1 text-right font-semibold">{report.fully_refunded_orders}</td></tr>
                <tr><td className="py-1">Net Revenue</td><td className="py-1 text-right font-semibold">{formatPKR(report.net_revenue)}</td></tr>
                <tr><td className="py-1">Net Tax Collected</td><td className="py-1 text-right font-semibold">{formatPKR(report.net_tax)}</td></tr>
                <tr><td className="py-1">Discounts</td><td className="py-1 text-right font-semibold">{formatPKR(report.total_discount)}</td></tr>
              </tbody>
            </table>
          </div>

          {/* ===== DETAIL SECTIONS ===== */}
          <div className="grid gap-6 lg:grid-cols-2 print:grid-cols-2 print:gap-4">
            {/* Cash Drawer */}
            {report.drawer && (
              <Card className="print:border print:border-gray-300 print:shadow-none print:rounded-none">
                <CardContent className="space-y-3 pt-6 print:pt-3 print:px-3">
                  <h2 className="font-semibold text-secondary-800 print:text-sm print:font-bold print:uppercase print:tracking-wide print:border-b print:border-gray-300 print:pb-1">
                    Cash Drawer
                    {report.drawer.session_status && (
                      <Badge
                        className={`ml-2 print:hidden ${
                          report.drawer.session_status === "open"
                            ? "bg-green-100 text-green-800"
                            : "bg-secondary-100 text-secondary-600"
                        }`}
                      >
                        {report.drawer.session_status}
                      </Badge>
                    )}
                    <span className="hidden print:inline ml-2 text-xs font-normal">
                      ({report.drawer.session_status})
                    </span>
                  </h2>
                  <div className="space-y-1 text-pos-sm print:text-xs">
                    <Row label="Opening Float" value={formatPKR(report.drawer.opening_float)} />
                    <Row label="Cash In (Sales)" value={formatPKR(report.drawer.cash_in)} />
                    <Row label="Cash Out (Change)" value={`-${formatPKR(report.drawer.cash_out_change)}`} />
                    <Row label="Cash Out (Refunds)" value={`-${formatPKR(report.drawer.cash_out_refund)}`} />
                    <div className="border-t pt-1" />
                    <Row label="Expected Balance" value={formatPKR(report.drawer.expected_balance)} bold />
                    {report.drawer.counted_balance != null && (
                      <>
                        <Row label="Counted Balance" value={formatPKR(report.drawer.counted_balance)} />
                        <Row
                          label="Variance"
                          value={formatPKR(report.drawer.variance ?? 0)}
                          bold
                          variant={
                            (report.drawer.variance ?? 0) === 0
                              ? "neutral"
                              : (report.drawer.variance ?? 0) > 0
                                ? "positive"
                                : "negative"
                          }
                        />
                      </>
                    )}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* By Channel */}
            <Card className="print:border print:border-gray-300 print:shadow-none print:rounded-none">
              <CardContent className="space-y-3 pt-6 print:pt-3 print:px-3">
                <h2 className="font-semibold text-secondary-800 print:text-sm print:font-bold print:uppercase print:tracking-wide print:border-b print:border-gray-300 print:pb-1">
                  Sales by Channel
                </h2>
                {report.by_channel.length === 0 ? (
                  <p className="text-pos-sm text-secondary-500">No sales</p>
                ) : (
                  <div className="space-y-2 text-pos-sm print:space-y-0 print:text-xs">
                    {report.by_channel.map((ch) => (
                      <div
                        key={ch.channel}
                        className="flex items-center justify-between rounded-lg bg-secondary-50 px-3 py-2 print:rounded-none print:bg-transparent print:px-0 print:py-1 print:border-b print:border-gray-100"
                      >
                        <span className="font-medium">
                          {channelLabels[ch.channel] ?? ch.channel}
                        </span>
                        <span>
                          {ch.orders} orders — {formatPKR(ch.revenue)}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* By Payment Method */}
            <Card className="print:border print:border-gray-300 print:shadow-none print:rounded-none">
              <CardContent className="space-y-3 pt-6 print:pt-3 print:px-3">
                <h2 className="font-semibold text-secondary-800 print:text-sm print:font-bold print:uppercase print:tracking-wide print:border-b print:border-gray-300 print:pb-1">
                  By Payment Method (Net)
                </h2>
                {report.by_payment_method.length === 0 ? (
                  <p className="text-pos-sm text-secondary-500">
                    No payments recorded
                  </p>
                ) : (
                  <div className="space-y-2 text-pos-sm print:space-y-0 print:text-xs">
                    {report.by_payment_method.map((pm) => (
                      <div
                        key={pm.method}
                        className="flex items-center justify-between rounded-lg bg-secondary-50 px-3 py-2 print:rounded-none print:bg-transparent print:px-0 print:py-1 print:border-b print:border-gray-100"
                      >
                        <div>
                          <div className="font-medium">{pm.method}</div>
                          <div className="text-xs text-secondary-500">
                            {pm.payment_count} payment{pm.payment_count === 1 ? "" : "s"}
                            {pm.refund_count > 0
                              ? ` | ${pm.refund_count} refund${pm.refund_count === 1 ? "" : "s"}`
                              : ""}
                          </div>
                        </div>
                        <div className="text-right">
                          <div className="font-semibold">
                            {formatPKR(pm.net_total)}
                          </div>
                          <div className="text-xs text-secondary-500">
                            Gross {formatPKR(pm.gross_total)}
                            {pm.refund_total > 0
                              ? ` | Refunds -${formatPKR(pm.refund_total)}`
                              : ""}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Order Status Breakdown */}
            <Card className="print:border print:border-gray-300 print:shadow-none print:rounded-none">
              <CardContent className="space-y-3 pt-6 print:pt-3 print:px-3">
                <h2 className="font-semibold text-secondary-800 print:text-sm print:font-bold print:uppercase print:tracking-wide print:border-b print:border-gray-300 print:pb-1">
                  Order Status
                </h2>
                <div className="flex flex-wrap gap-2 print:gap-1">
                  {report.by_status.map((s) => (
                    <Badge key={s.status} variant="outline" className="text-pos-sm print:text-xs print:rounded-none print:border-gray-400">
                      {s.status}: {s.count}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Top Items */}
          {report.top_items.length > 0 && (
            <Card className="print:border print:border-gray-300 print:shadow-none print:rounded-none print-section">
              <CardContent className="pt-6 print:pt-3 print:px-3">
                <h2 className="mb-3 font-semibold text-secondary-800 print:text-sm print:font-bold print:uppercase print:tracking-wide print:border-b print:border-gray-300 print:pb-1 print:mb-2">
                  Top 10 Items
                </h2>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-pos-sm print:text-xs">
                    <thead>
                      <tr className="border-b text-secondary-500 print:text-gray-600">
                        <th className="pb-2 font-medium print:pb-1">#</th>
                        <th className="pb-2 font-medium print:pb-1">Item</th>
                        <th className="pb-2 font-medium text-right print:pb-1">Qty</th>
                        <th className="pb-2 font-medium text-right print:pb-1">Revenue</th>
                      </tr>
                    </thead>
                    <tbody>
                      {report.top_items.map((item, i) => (
                        <tr key={i} className="border-b last:border-0">
                          <td className="py-2 text-secondary-500 print:py-1">{i + 1}</td>
                          <td className="py-2 font-medium print:py-1">{item.name}</td>
                          <td className="py-2 text-right print:py-1">{item.quantity}</td>
                          <td className="py-2 text-right print:py-1">
                            {formatPKR(item.revenue)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Print footer */}
          <div className="hidden print:block print:mt-6 print:pt-3 print:border-t print:border-gray-300 print:text-center print:text-xs print:text-gray-400">
            End of Z-Report — {selectedDate}
          </div>
        </div>
      )}
    </div>
  );
}

/* ---------- helpers ---------- */

function KpiCard({
  icon,
  label,
  value,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
}) {
  return (
    <Card>
      <CardContent className="flex items-center gap-3 pt-6">
        <div className="rounded-lg bg-primary-100 p-2 text-primary-600">
          {icon}
        </div>
        <div>
          <p className="text-pos-sm text-secondary-500">{label}</p>
          <p className="text-pos-lg font-bold text-secondary-900">{value}</p>
        </div>
      </CardContent>
    </Card>
  );
}

function Row({
  label,
  value,
  bold,
  variant,
}: {
  label: string;
  value: string;
  bold?: boolean;
  variant?: "neutral" | "positive" | "negative";
}) {
  const variantClass =
    variant === "positive"
      ? "text-green-600"
      : variant === "negative"
        ? "text-red-600"
        : "";

  return (
    <div className="flex justify-between">
      <span className={bold ? "font-semibold" : ""}>{label}</span>
      <span className={`${bold ? "font-semibold" : ""} ${variantClass}`}>
        {value}
      </span>
    </div>
  );
}

export default ZReportPage;
